name: CI
on: [push, pull_request]

jobs:
    build:
        name: Test macOS
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v1
            - name: Test macOS
              run: xcodebuild clean test -project Space\ Golf/Space\ Golf.xcodeproj -scheme 'Space Golf Tests' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
