name: CI
on: [push, pull_request]

jobs:
    build:
        name: Build macOS
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build macOS
              run: xcodebuild clean build -project Gravity\ Putt/Gravity\ Putt.xcodeproj -scheme 'Gravity Putt macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
