name: CI
on: [push, pull_request]

jobs:
    build:
        
        name: Test
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: xcodebuild -list
