name: CI
on: [push, pull_request]

jobs:
    test:
        name: Test
        runs-on: macOS-latest
        strategy:
            matrix:
                destination: ["platform=iOS Simulator,OS=13.4,name=iPhone 11"]
        steps:
            - name: Build
              run: xcodebuild clean build -project 'Space Golf/Space Golf.xcodeproj' -scheme 'Space Golf iOS' -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
              env:
                  destination: $
